# version: "3.5"
services:
  # Node.js App Service
  eseller-node-backend:
    build: .
    container_name: eseller-node-server
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
    volumes:
      # Syncs your local code with the container for live-reloading
      - .:/app
      # Prevents local node_modules from overwriting the container's node_modules
      - /app/node_modules
 
    networks:
      - tj-net
 
networks:
  tj-net:
    name: tj-net
